[build]
  # No build command needed for plain HTML/CSS/JS
  command = ""
  # Deploy everything in the repo root
  publish = "."

# Redirect all routes to index.html (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
